import type { ArenaEnemyKind, ArenaEnemyShape, ArenaWeapon } from './types';

export const ARENA_PLAYER_HALF_WIDTH = 22;
export const ARENA_PLAYER_RENDER_HALF_WIDTH = 37;
export const ARENA_PLAYER_HITBOX_HALF_WIDTH = 16;
export const ARENA_PLAYER_HEIGHT = 28;
export const ARENA_PLAYER_MARGIN = 14;
export const ARENA_PLAYER_FLOOR_OFFSET = 60;
export const ARENA_TIER_DURATION_SECONDS = 15;
export const ARENA_MAX_FRAME_DELTA_SECONDS = 0.1;
export const ARENA_FIXED_STEP_SECONDS = 1 / 60;
export const ARENA_MAX_CATCH_UP_STEPS = 5;
export const ARENA_MAX_ACTIVE_EFFECTS = 30;
export const ARENA_ENEMY_ZONE_RATIO = 0.46;
export const ARENA_MIN_ENEMY_CRUISE_Y_RATIO = 0.15;
export const ARENA_MAX_ENEMY_CRUISE_Y_RATIO = 0.41;
export const ARENA_SHIELD_REGEN_DELAY_SECONDS = 2.2;
export const ARENA_SHIELD_REGEN_PER_SECOND = 11;
export const ARENA_VERSION_LABEL = 'v0.79';

export const ARENA_ENEMY_ORDER: ArenaEnemyKind[] = [
  'hover',
  'burst',
  'tank',
  'orbiter',
  'sniper',
  'bomber',
  'interceptor',
  'warden',
  'lancer',
  'carrier',
  'artillery',
  'weaver',
  'conductor',
  'raider',
  'hunter',
  'prismBoss',
  'hiveCarrierBoss',
  'vectorLoomBoss',
  'eclipseTalonBoss',
];

export const BASE_ARENA_WEAPON: ArenaWeapon = {
  damage: 12,
  fireInterval: 0.11,
  shotCount: 1,
  pierce: 0,
  bulletSpeed: 980,
  bulletSize: 8,
  spread: 14,
};

export const ARENA_ENEMY_COLORS: Record<ArenaEnemyKind, string> = {
  hover: '#57E0FF',
  burst: '#FF66D6',
  tank: '#FFB06A',
  orbiter: '#63FFF2',
  sniper: '#FF98E8',
  bomber: '#FF946A',
  interceptor: '#9F8CFF',
  warden: '#65F5FF',
  lancer: '#FFC37C',
  carrier: '#59F2D0',
  artillery: '#FFBA86',
  weaver: '#9BB0FF',
  conductor: '#FFE072',
  raider: '#FF8C5B',
  hunter: '#D89FFF',
  prismBoss: '#FF59C8',
  hiveCarrierBoss: '#63F2D7',
  vectorLoomBoss: '#AF9BFF',
  eclipseTalonBoss: '#FFB977',
};

export const ARENA_ENEMY_SHAPES: Record<ArenaEnemyKind, ArenaEnemyShape> = {
  hover: 'circle',
  burst: 'diamond',
  tank: 'square',
  orbiter: 'circle',
  sniper: 'square',
  bomber: 'square',
  interceptor: 'diamond',
  warden: 'square',
  lancer: 'diamond',
  carrier: 'square',
  artillery: 'square',
  weaver: 'diamond',
  conductor: 'diamond',
  raider: 'diamond',
  hunter: 'diamond',
  prismBoss: 'diamond',
  hiveCarrierBoss: 'square',
  vectorLoomBoss: 'diamond',
  eclipseTalonBoss: 'diamond',
};

export const ARENA_ENEMY_CONFIG: Record<
  ArenaEnemyKind,
  {
    size: number;
    baseHealth: number;
    healthPerTier: number;
    strafeSpeed: number;
    descendSpeed: number;
    fireInterval: number;
    windupDuration: number;
    bulletSpeed: number;
    bulletDamage: number;
    bulletSize: number;
    reward: number;
    burstCount: number;
    spreadAngle: number;
    bobAmplitude: number;
  }
> = {
  hover: {
    size: 38,
    baseHealth: 28,
    healthPerTier: 6,
    strafeSpeed: 58,
    descendSpeed: 108,
    fireInterval: 1.55,
    windupDuration: 0.16,
    bulletSpeed: 238,
    bulletDamage: 8,
    bulletSize: 9,
    reward: 90,
    burstCount: 1,
    spreadAngle: 0,
    bobAmplitude: 8,
  },
  burst: {
    size: 46,
    baseHealth: 48,
    healthPerTier: 9,
    strafeSpeed: 44,
    descendSpeed: 96,
    fireInterval: 2.45,
    windupDuration: 0.42,
    bulletSpeed: 255,
    bulletDamage: 7,
    bulletSize: 8,
    reward: 140,
    burstCount: 3,
    spreadAngle: 0.28,
    bobAmplitude: 6,
  },
  tank: {
    size: 58,
    baseHealth: 88,
    healthPerTier: 16,
    strafeSpeed: 28,
    descendSpeed: 84,
    fireInterval: 3.15,
    windupDuration: 0.6,
    bulletSpeed: 220,
    bulletDamage: 16,
    bulletSize: 12,
    reward: 240,
    burstCount: 1,
    spreadAngle: 0,
    bobAmplitude: 4,
  },
  orbiter: {
    size: 44,
    baseHealth: 54,
    healthPerTier: 10,
    strafeSpeed: 46,
    descendSpeed: 96,
    fireInterval: 2.2,
    windupDuration: 0.32,
    bulletSpeed: 262,
    bulletDamage: 9,
    bulletSize: 8,
    reward: 165,
    burstCount: 2,
    spreadAngle: 0.34,
    bobAmplitude: 16,
  },
  sniper: {
    size: 50,
    baseHealth: 72,
    healthPerTier: 12,
    strafeSpeed: 24,
    descendSpeed: 90,
    fireInterval: 3.55,
    windupDuration: 0.82,
    bulletSpeed: 410,
    bulletDamage: 22,
    bulletSize: 10,
    reward: 230,
    burstCount: 1,
    spreadAngle: 0,
    bobAmplitude: 0,
  },
  bomber: {
    size: 54,
    baseHealth: 80,
    healthPerTier: 14,
    strafeSpeed: 34,
    descendSpeed: 88,
    fireInterval: 2.95,
    windupDuration: 0.6,
    bulletSpeed: 236,
    bulletDamage: 15,
    bulletSize: 11,
    reward: 255,
    burstCount: 3,
    spreadAngle: 0.16,
    bobAmplitude: 0,
  },
  interceptor: {
    size: 64,
    baseHealth: 220,
    healthPerTier: 34,
    strafeSpeed: 74,
    descendSpeed: 112,
    fireInterval: 1.9,
    windupDuration: 0.46,
    bulletSpeed: 290,
    bulletDamage: 10,
    bulletSize: 9,
    reward: 420,
    burstCount: 5,
    spreadAngle: 0.2,
    bobAmplitude: 4,
  },
  warden: {
    size: 50,
    baseHealth: 92,
    healthPerTier: 16,
    strafeSpeed: 30,
    descendSpeed: 92,
    fireInterval: 2.85,
    windupDuration: 0.48,
    bulletSpeed: 252,
    bulletDamage: 10,
    bulletSize: 9,
    reward: 245,
    burstCount: 2,
    spreadAngle: 0.16,
    bobAmplitude: 4,
  },
  lancer: {
    size: 56,
    baseHealth: 104,
    healthPerTier: 18,
    strafeSpeed: 56,
    descendSpeed: 100,
    fireInterval: 3.35,
    windupDuration: 0.92,
    bulletSpeed: 520,
    bulletDamage: 16,
    bulletSize: 8,
    reward: 285,
    burstCount: 1,
    spreadAngle: 0,
    bobAmplitude: 5,
  },
  carrier: {
    size: 68,
    baseHealth: 148,
    healthPerTier: 24,
    strafeSpeed: 26,
    descendSpeed: 88,
    fireInterval: 3.6,
    windupDuration: 0.66,
    bulletSpeed: 246,
    bulletDamage: 13,
    bulletSize: 10,
    reward: 335,
    burstCount: 2,
    spreadAngle: 0.14,
    bobAmplitude: 3,
  },
  artillery: {
    size: 64,
    baseHealth: 134,
    healthPerTier: 22,
    strafeSpeed: 20,
    descendSpeed: 82,
    fireInterval: 4.1,
    windupDuration: 0.88,
    bulletSpeed: 208,
    bulletDamage: 18,
    bulletSize: 12,
    reward: 320,
    burstCount: 1,
    spreadAngle: 0,
    bobAmplitude: 2,
  },
  weaver: {
    size: 60,
    baseHealth: 142,
    healthPerTier: 24,
    strafeSpeed: 30,
    descendSpeed: 88,
    fireInterval: 3.7,
    windupDuration: 0.86,
    bulletSpeed: 236,
    bulletDamage: 15,
    bulletSize: 10,
    reward: 332,
    burstCount: 1,
    spreadAngle: 0,
    bobAmplitude: 4,
  },
  conductor: {
    size: 58,
    baseHealth: 128,
    healthPerTier: 22,
    strafeSpeed: 58,
    descendSpeed: 94,
    fireInterval: 3.25,
    windupDuration: 0.9,
    bulletSpeed: 320,
    bulletDamage: 15,
    bulletSize: 9,
    reward: 318,
    burstCount: 2,
    spreadAngle: 0.12,
    bobAmplitude: 5,
  },
  raider: {
    size: 52,
    baseHealth: 118,
    healthPerTier: 19,
    strafeSpeed: 78,
    descendSpeed: 104,
    fireInterval: 2.65,
    windupDuration: 0.62,
    bulletSpeed: 360,
    bulletDamage: 13,
    bulletSize: 8,
    reward: 300,
    burstCount: 3,
    spreadAngle: 0.18,
    bobAmplitude: 7,
  },
  hunter: {
    size: 54,
    baseHealth: 136,
    healthPerTier: 22,
    strafeSpeed: 48,
    descendSpeed: 94,
    fireInterval: 3.25,
    windupDuration: 0.92,
    bulletSpeed: 430,
    bulletDamage: 17,
    bulletSize: 8,
    reward: 330,
    burstCount: 2,
    spreadAngle: 0.08,
    bobAmplitude: 5,
  },
  prismBoss: {
    size: 96,
    baseHealth: 680,
    healthPerTier: 120,
    strafeSpeed: 36,
    descendSpeed: 80,
    fireInterval: 2.55,
    windupDuration: 0.62,
    bulletSpeed: 272,
    bulletDamage: 15,
    bulletSize: 11,
    reward: 980,
    burstCount: 5,
    spreadAngle: 0.22,
    bobAmplitude: 0,
  },
  hiveCarrierBoss: {
    size: 114,
    baseHealth: 760,
    healthPerTier: 132,
    strafeSpeed: 28,
    descendSpeed: 76,
    fireInterval: 2.9,
    windupDuration: 0.7,
    bulletSpeed: 244,
    bulletDamage: 16,
    bulletSize: 12,
    reward: 1100,
    burstCount: 4,
    spreadAngle: 0.18,
    bobAmplitude: 0,
  },
  vectorLoomBoss: {
    size: 108,
    baseHealth: 840,
    healthPerTier: 140,
    strafeSpeed: 32,
    descendSpeed: 78,
    fireInterval: 2.82,
    windupDuration: 0.74,
    bulletSpeed: 254,
    bulletDamage: 17,
    bulletSize: 11,
    reward: 1160,
    burstCount: 4,
    spreadAngle: 0.17,
    bobAmplitude: 0,
  },
  eclipseTalonBoss: {
    size: 112,
    baseHealth: 900,
    healthPerTier: 148,
    strafeSpeed: 44,
    descendSpeed: 78,
    fireInterval: 2.62,
    windupDuration: 0.72,
    bulletSpeed: 340,
    bulletDamage: 18,
    bulletSize: 10,
    reward: 1220,
    burstCount: 5,
    spreadAngle: 0.16,
    bobAmplitude: 0,
  },
};
