import { ARENA_BUILD_META, ARENA_BUILD_ORDER } from './builds';
import type {
  ArenaBuildId,
  ArenaBuildValueMap,
  ArenaCosmeticDefinition,
  ArenaCosmeticId,
  ArenaCosmeticSlot,
  ArenaUnlockId,
} from './types';

type ArenaGlobalCosmeticSlot = Extract<ArenaCosmeticSlot, 'banner' | 'codexFrame'>;
type ArenaBuildCosmeticSlot = Extract<ArenaCosmeticSlot, 'buildAccent' | 'buildCrest'>;

export const ARENA_COSMETIC_ORDER: ArenaCosmeticId[] = [
  'bannerDefault',
  'bannerPrismShard',
  'bannerHiveTrace',
  'bannerLoomStatic',
  'bannerEclipseCut',
  'bannerTriadBreaker',
  'bannerDeepCycle',
  'codexFrameDefault',
  'codexFrameFullSpectrum',
  'codexFrameEndlessApex',
  'codexFrameTriadGrid',
  'codexFrameFullRotation',
  'codexFrameThreatCartographer',
  'codexFrameOuterLimit',
  'railFocusAccentDefault',
  'railFocusAccentHalo',
  'railFocusAccentApexRail',
  'novaBloomAccentDefault',
  'novaBloomAccentEcho',
  'novaBloomAccentSolarCrown',
  'missileCommandAccentDefault',
  'missileCommandAccentStrikeMesh',
  'missileCommandAccentSiegeMesh',
  'fractureCoreAccentDefault',
  'fractureCoreAccentFractureVein',
  'fractureCoreAccentSingularityVein',
  'railFocusCrestDefault',
  'railFocusCrestZenith',
  'novaBloomCrestDefault',
  'novaBloomCrestSolarBloom',
  'missileCommandCrestDefault',
  'missileCommandCrestOrdnanceCrown',
  'fractureCoreCrestDefault',
  'fractureCoreCrestShatterCrown',
];

export const ARENA_COSMETIC_DEFINITIONS: Record<ArenaCosmeticId, ArenaCosmeticDefinition> = {
  bannerDefault: {
    id: 'bannerDefault',
    label: 'Default Banner',
    description: 'Standard arena command strip with clean blue framing.',
    slot: 'banner',
    buildId: null,
    sourceType: 'default',
    rarity: 'common',
    rewardUnlockId: null,
    primaryColor: '#193349',
    secondaryColor: '#4A7AA3',
    detailColor: '#B4D8FF',
    glowColor: '#D8EEFF',
  },
  bannerPrismShard: {
    id: 'bannerPrismShard',
    label: 'Boss Banner: Prism Shard',
    description: 'Iridescent prism lattice recovered from the first Prism Core clear.',
    slot: 'banner',
    buildId: null,
    sourceType: 'reward',
    rarity: 'rare',
    rewardUnlockId: 'prismCoreFirstClear',
    primaryColor: '#2C2453',
    secondaryColor: '#FF8AC3',
    detailColor: '#FFE8F5',
    glowColor: '#FFD2E9',
  },
  bannerHiveTrace: {
    id: 'bannerHiveTrace',
    label: 'Boss Banner: Hive Trace',
    description: 'Emerald carrier signal bands recovered from the first Hive Carrier clear.',
    slot: 'banner',
    buildId: null,
    sourceType: 'reward',
    rarity: 'rare',
    rewardUnlockId: 'hiveCarrierFirstClear',
    primaryColor: '#163A31',
    secondaryColor: '#3E9A84',
    detailColor: '#93F0D5',
    glowColor: '#C7FFF1',
  },
  bannerLoomStatic: {
    id: 'bannerLoomStatic',
    label: 'Boss Banner: Loom Static',
    description: 'Cold lattice bands recovered from the first Vector Loom clear.',
    slot: 'banner',
    buildId: null,
    sourceType: 'reward',
    rarity: 'epic',
    rewardUnlockId: 'vectorLoomFirstClear',
    primaryColor: '#1B244B',
    secondaryColor: '#5E7CCF',
    detailColor: '#C7D8FF',
    glowColor: '#EEF4FF',
  },
  bannerEclipseCut: {
    id: 'bannerEclipseCut',
    label: 'Boss Banner: Eclipse Cut',
    description: 'Angular flank-strike strip recovered from the first Eclipse Talon clear.',
    slot: 'banner',
    buildId: null,
    sourceType: 'reward',
    rarity: 'epic',
    rewardUnlockId: 'eclipseTalonFirstClear',
    primaryColor: '#2B1F2A',
    secondaryColor: '#FFB36E',
    detailColor: '#FFF0C8',
    glowColor: '#FFD49A',
  },
  bannerTriadBreaker: {
    id: 'bannerTriadBreaker',
    label: 'Boss Banner: Triad Breaker',
    description: 'Three-boss run strip awarded for breaking Prism, Hive, and Vector in one deployment.',
    slot: 'banner',
    buildId: null,
    sourceType: 'reward',
    rarity: 'epic',
    rewardUnlockId: 'singleRunBossTriadClear',
    primaryColor: '#232042',
    secondaryColor: '#77E3D1',
    detailColor: '#FFE49E',
    glowColor: '#F3ECFF',
  },
  bannerDeepCycle: {
    id: 'bannerDeepCycle',
    label: 'Boss Banner: Deep Cycle',
    description: 'Long-run command banner awarded for reaching pressure tier 45.',
    slot: 'banner',
    buildId: null,
    sourceType: 'reward',
    rarity: 'epic',
    rewardUnlockId: 'tier45Clear',
    primaryColor: '#121F38',
    secondaryColor: '#6F8DFF',
    detailColor: '#FFE0A1',
    glowColor: '#BFD4FF',
  },
  codexFrameDefault: {
    id: 'codexFrameDefault',
    label: 'Default Codex Frame',
    description: 'Baseline tactical frame used for arena records and collection panels.',
    slot: 'codexFrame',
    buildId: null,
    sourceType: 'default',
    rarity: 'common',
    rewardUnlockId: null,
    primaryColor: '#1A2D42',
    secondaryColor: '#547897',
    detailColor: '#A7C6E7',
    glowColor: '#D5EAFF',
  },
  codexFrameFullSpectrum: {
    id: 'codexFrameFullSpectrum',
    label: 'Codex Frame: Full Spectrum',
    description: 'Full-spectrum prism frame awarded for completing every enemy signal entry.',
    slot: 'codexFrame',
    buildId: null,
    sourceType: 'reward',
    rarity: 'rare',
    rewardUnlockId: 'enemyCodexComplete',
    primaryColor: '#31245C',
    secondaryColor: '#63B9FF',
    detailColor: '#FFD976',
    glowColor: '#FFB7D9',
  },
  codexFrameEndlessApex: {
    id: 'codexFrameEndlessApex',
    label: 'Codex Frame: Endless Apex',
    description: 'High-tier command frame awarded for reaching pressure tier 24 in a single run.',
    slot: 'codexFrame',
    buildId: null,
    sourceType: 'reward',
    rarity: 'epic',
    rewardUnlockId: 'tier24Clear',
    primaryColor: '#14263C',
    secondaryColor: '#8ED6FF',
    detailColor: '#FFF0BD',
    glowColor: '#E8F7FF',
  },
  codexFrameTriadGrid: {
    id: 'codexFrameTriadGrid',
    label: 'Codex Frame: Triad Grid',
    description: 'Triangulated tactical frame awarded for clearing every active boss at least once.',
    slot: 'codexFrame',
    buildId: null,
    sourceType: 'reward',
    rarity: 'epic',
    rewardUnlockId: 'bossTriadComplete',
    primaryColor: '#18263E',
    secondaryColor: '#7DA8FF',
    detailColor: '#FFE09B',
    glowColor: '#DCE8FF',
  },
  codexFrameFullRotation: {
    id: 'codexFrameFullRotation',
    label: 'Codex Frame: Full Rotation',
    description: 'Four-boss rotation frame awarded for clearing every active boss at least once.',
    slot: 'codexFrame',
    buildId: null,
    sourceType: 'reward',
    rarity: 'epic',
    rewardUnlockId: 'bossFullRotationComplete',
    primaryColor: '#172139',
    secondaryColor: '#D8B9FF',
    detailColor: '#FFE3A8',
    glowColor: '#F1E5FF',
  },
  codexFrameThreatCartographer: {
    id: 'codexFrameThreatCartographer',
    label: 'Codex Frame: Threat Cartographer',
    description: 'Route-mapping codex frame awarded for reaching pressure tier 30.',
    slot: 'codexFrame',
    buildId: null,
    sourceType: 'reward',
    rarity: 'rare',
    rewardUnlockId: 'tier30Clear',
    primaryColor: '#122A3D',
    secondaryColor: '#5ED2FF',
    detailColor: '#CFF4FF',
    glowColor: '#E7FBFF',
  },
  codexFrameOuterLimit: {
    id: 'codexFrameOuterLimit',
    label: 'Codex Frame: Outer Limit',
    description: 'Outer-sector codex frame awarded for reaching pressure tier 60.',
    slot: 'codexFrame',
    buildId: null,
    sourceType: 'reward',
    rarity: 'epic',
    rewardUnlockId: 'tier60Clear',
    primaryColor: '#171E32',
    secondaryColor: '#B3C7FF',
    detailColor: '#F4F8FF',
    glowColor: '#FFFFFF',
  },
  railFocusAccentDefault: {
    id: 'railFocusAccentDefault',
    label: 'Rail Focus Accent: Standard',
    description: 'Default Rail Focus trim with cool lane-control highlights.',
    slot: 'buildAccent',
    buildId: 'railFocus',
    sourceType: 'default',
    rarity: 'common',
    rewardUnlockId: null,
    primaryColor: ARENA_BUILD_META.railFocus.accent,
    secondaryColor: '#2D79BD',
    detailColor: '#FFF0CA',
    glowColor: '#6FE7FF',
  },
  railFocusAccentHalo: {
    id: 'railFocusAccentHalo',
    label: 'Build Accent: Rail Halo',
    description: 'Brightened Rail Focus trim unlocked at mastery rank 4.',
    slot: 'buildAccent',
    buildId: 'railFocus',
    sourceType: 'reward',
    rarity: 'rare',
    rewardUnlockId: 'railFocusMastery4',
    primaryColor: '#D9F0FF',
    secondaryColor: '#69B8FF',
    detailColor: '#F9F6D8',
    glowColor: '#F3FCFF',
  },
  railFocusAccentApexRail: {
    id: 'railFocusAccentApexRail',
    label: 'Rail Focus: Apex Rail',
    description: 'Razor-bright Rail Focus trim unlocked at mastery rank 10.',
    slot: 'buildAccent',
    buildId: 'railFocus',
    sourceType: 'reward',
    rarity: 'epic',
    rewardUnlockId: 'railFocusMastery10',
    primaryColor: '#F5FDFF',
    secondaryColor: '#2DDCFF',
    detailColor: '#FFF8D6',
    glowColor: '#F7FFFF',
  },
  novaBloomAccentDefault: {
    id: 'novaBloomAccentDefault',
    label: 'Nova Bloom Accent: Standard',
    description: 'Default Nova Bloom trim with rose fan highlights.',
    slot: 'buildAccent',
    buildId: 'novaBloom',
    sourceType: 'default',
    rarity: 'common',
    rewardUnlockId: null,
    primaryColor: ARENA_BUILD_META.novaBloom.accent,
    secondaryColor: '#C65991',
    detailColor: '#FFF0CA',
    glowColor: '#FFD9EB',
  },
  novaBloomAccentEcho: {
    id: 'novaBloomAccentEcho',
    label: 'Build Accent: Bloom Echo',
    description: 'Luminous bloom trim unlocked at mastery rank 4.',
    slot: 'buildAccent',
    buildId: 'novaBloom',
    sourceType: 'reward',
    rarity: 'rare',
    rewardUnlockId: 'novaBloomMastery4',
    primaryColor: '#FFD9EC',
    secondaryColor: '#FF82C4',
    detailColor: '#FFF4B8',
    glowColor: '#FFF2D6',
  },
  novaBloomAccentSolarCrown: {
    id: 'novaBloomAccentSolarCrown',
    label: 'Nova Bloom: Solar Crown',
    description: 'Corona-lit Nova Bloom trim unlocked at mastery rank 10.',
    slot: 'buildAccent',
    buildId: 'novaBloom',
    sourceType: 'reward',
    rarity: 'epic',
    rewardUnlockId: 'novaBloomMastery10',
    primaryColor: '#FFF1B8',
    secondaryColor: '#FF6AB7',
    detailColor: '#FFFBE8',
    glowColor: '#FFF7C8',
  },
  missileCommandAccentDefault: {
    id: 'missileCommandAccentDefault',
    label: 'Missile Command Accent: Standard',
    description: 'Default Missile Command trim with warm ordnance highlights.',
    slot: 'buildAccent',
    buildId: 'missileCommand',
    sourceType: 'default',
    rarity: 'common',
    rewardUnlockId: null,
    primaryColor: ARENA_BUILD_META.missileCommand.accent,
    secondaryColor: '#C98732',
    detailColor: '#FFF0CA',
    glowColor: '#FFE2B6',
  },
  missileCommandAccentStrikeMesh: {
    id: 'missileCommandAccentStrikeMesh',
    label: 'Build Accent: Strike Mesh',
    description: 'High-visibility strike mesh trim unlocked at mastery rank 4.',
    slot: 'buildAccent',
    buildId: 'missileCommand',
    sourceType: 'reward',
    rarity: 'rare',
    rewardUnlockId: 'missileCommandMastery4',
    primaryColor: '#FFF0B8',
    secondaryColor: '#FFAF57',
    detailColor: '#FFF6DE',
    glowColor: '#FFF9EC',
  },
  missileCommandAccentSiegeMesh: {
    id: 'missileCommandAccentSiegeMesh',
    label: 'Missile Command: Siege Mesh',
    description: 'High-tier ordnance mesh unlocked at mastery rank 10.',
    slot: 'buildAccent',
    buildId: 'missileCommand',
    sourceType: 'reward',
    rarity: 'epic',
    rewardUnlockId: 'missileCommandMastery10',
    primaryColor: '#FFE7A3',
    secondaryColor: '#FF8A3D',
    detailColor: '#FFF8DF',
    glowColor: '#FFF3CB',
  },
  fractureCoreAccentDefault: {
    id: 'fractureCoreAccentDefault',
    label: 'Fracture Core Accent: Standard',
    description: 'Default Fracture Core trim with cold shard highlights.',
    slot: 'buildAccent',
    buildId: 'fractureCore',
    sourceType: 'default',
    rarity: 'common',
    rewardUnlockId: null,
    primaryColor: ARENA_BUILD_META.fractureCore.accent,
    secondaryColor: '#6B8FDE',
    detailColor: '#FFF0CA',
    glowColor: '#DCEBFF',
  },
  fractureCoreAccentFractureVein: {
    id: 'fractureCoreAccentFractureVein',
    label: 'Build Accent: Fracture Vein',
    description: 'Crystalline shard trim unlocked at mastery rank 4.',
    slot: 'buildAccent',
    buildId: 'fractureCore',
    sourceType: 'reward',
    rarity: 'rare',
    rewardUnlockId: 'fractureCoreMastery4',
    primaryColor: '#E7F2FF',
    secondaryColor: '#96B7FF',
    detailColor: '#FFF4D8',
    glowColor: '#F5FBFF',
  },
  fractureCoreAccentSingularityVein: {
    id: 'fractureCoreAccentSingularityVein',
    label: 'Fracture Core: Singularity Vein',
    description: 'Dense singularity trim unlocked at mastery rank 10.',
    slot: 'buildAccent',
    buildId: 'fractureCore',
    sourceType: 'reward',
    rarity: 'epic',
    rewardUnlockId: 'fractureCoreMastery10',
    primaryColor: '#E9F2FF',
    secondaryColor: '#6F7CFF',
    detailColor: '#FFF7E5',
    glowColor: '#FFFFFF',
  },
  railFocusCrestDefault: {
    id: 'railFocusCrestDefault',
    label: 'Rail Focus Crest: Standard',
    description: 'Default Rail Focus crest marker.',
    slot: 'buildCrest',
    buildId: 'railFocus',
    sourceType: 'default',
    rarity: 'common',
    rewardUnlockId: null,
    primaryColor: '#D8EEFF',
    secondaryColor: '#5DAEFF',
    detailColor: '#FFFFFF',
    glowColor: '#DFF8FF',
    emblemKey: 'rail-default',
  },
  railFocusCrestZenith: {
    id: 'railFocusCrestZenith',
    label: 'Build Crest: Rail Zenith',
    description: 'Zenith crest unlocked at Rail Focus mastery rank 8.',
    slot: 'buildCrest',
    buildId: 'railFocus',
    sourceType: 'reward',
    rarity: 'epic',
    rewardUnlockId: 'railFocusMastery8',
    primaryColor: '#F1FAFF',
    secondaryColor: '#9BD7FF',
    detailColor: '#FFF2C7',
    glowColor: '#F9FDFF',
    emblemKey: 'rail-zenith',
  },
  novaBloomCrestDefault: {
    id: 'novaBloomCrestDefault',
    label: 'Nova Bloom Crest: Standard',
    description: 'Default Nova Bloom crest marker.',
    slot: 'buildCrest',
    buildId: 'novaBloom',
    sourceType: 'default',
    rarity: 'common',
    rewardUnlockId: null,
    primaryColor: '#FFE1EE',
    secondaryColor: '#FF8BC8',
    detailColor: '#FFF7D5',
    glowColor: '#FFF1F7',
    emblemKey: 'nova-default',
  },
  novaBloomCrestSolarBloom: {
    id: 'novaBloomCrestSolarBloom',
    label: 'Build Crest: Solar Bloom',
    description: 'Solar bloom crest unlocked at Nova Bloom mastery rank 8.',
    slot: 'buildCrest',
    buildId: 'novaBloom',
    sourceType: 'reward',
    rarity: 'epic',
    rewardUnlockId: 'novaBloomMastery8',
    primaryColor: '#FFF0C2',
    secondaryColor: '#FF9FD1',
    detailColor: '#FFFBEA',
    glowColor: '#FFF7D5',
    emblemKey: 'nova-solar',
  },
  missileCommandCrestDefault: {
    id: 'missileCommandCrestDefault',
    label: 'Missile Command Crest: Standard',
    description: 'Default Missile Command crest marker.',
    slot: 'buildCrest',
    buildId: 'missileCommand',
    sourceType: 'default',
    rarity: 'common',
    rewardUnlockId: null,
    primaryColor: '#FFF1D0',
    secondaryColor: '#FFBC69',
    detailColor: '#FFFFFF',
    glowColor: '#FFF6E6',
    emblemKey: 'missile-default',
  },
  missileCommandCrestOrdnanceCrown: {
    id: 'missileCommandCrestOrdnanceCrown',
    label: 'Build Crest: Ordnance Crown',
    description: 'Ordnance crown crest unlocked at Missile Command mastery rank 8.',
    slot: 'buildCrest',
    buildId: 'missileCommand',
    sourceType: 'reward',
    rarity: 'epic',
    rewardUnlockId: 'missileCommandMastery8',
    primaryColor: '#FFF5D7',
    secondaryColor: '#FFD877',
    detailColor: '#FFFDF3',
    glowColor: '#FFF8E7',
    emblemKey: 'missile-crown',
  },
  fractureCoreCrestDefault: {
    id: 'fractureCoreCrestDefault',
    label: 'Fracture Core Crest: Standard',
    description: 'Default Fracture Core crest marker.',
    slot: 'buildCrest',
    buildId: 'fractureCore',
    sourceType: 'default',
    rarity: 'common',
    rewardUnlockId: null,
    primaryColor: '#E2EEFF',
    secondaryColor: '#96B4FF',
    detailColor: '#FFF3D8',
    glowColor: '#F5FAFF',
    emblemKey: 'fracture-default',
  },
  fractureCoreCrestShatterCrown: {
    id: 'fractureCoreCrestShatterCrown',
    label: 'Build Crest: Shatter Crown',
    description: 'Shatter crown crest unlocked at Fracture Core mastery rank 8.',
    slot: 'buildCrest',
    buildId: 'fractureCore',
    sourceType: 'reward',
    rarity: 'epic',
    rewardUnlockId: 'fractureCoreMastery8',
    primaryColor: '#F2F7FF',
    secondaryColor: '#B6CBFF',
    detailColor: '#FFF7E5',
    glowColor: '#FBFDFF',
    emblemKey: 'fracture-crown',
  },
};

const ARENA_GLOBAL_COSMETIC_ORDER: Record<ArenaGlobalCosmeticSlot, ArenaCosmeticId[]> = {
  banner: [
    'bannerDefault',
    'bannerPrismShard',
    'bannerHiveTrace',
    'bannerLoomStatic',
    'bannerEclipseCut',
    'bannerTriadBreaker',
    'bannerDeepCycle',
  ],
  codexFrame: [
    'codexFrameDefault',
    'codexFrameFullSpectrum',
    'codexFrameEndlessApex',
    'codexFrameTriadGrid',
    'codexFrameFullRotation',
    'codexFrameThreatCartographer',
    'codexFrameOuterLimit',
  ],
};

const ARENA_BUILD_COSMETIC_ORDER: ArenaBuildValueMap<Record<ArenaBuildCosmeticSlot, ArenaCosmeticId[]>> = {
  railFocus: {
    buildAccent: ['railFocusAccentDefault', 'railFocusAccentHalo', 'railFocusAccentApexRail'],
    buildCrest: ['railFocusCrestDefault', 'railFocusCrestZenith'],
  },
  novaBloom: {
    buildAccent: ['novaBloomAccentDefault', 'novaBloomAccentEcho', 'novaBloomAccentSolarCrown'],
    buildCrest: ['novaBloomCrestDefault', 'novaBloomCrestSolarBloom'],
  },
  missileCommand: {
    buildAccent: [
      'missileCommandAccentDefault',
      'missileCommandAccentStrikeMesh',
      'missileCommandAccentSiegeMesh',
    ],
    buildCrest: ['missileCommandCrestDefault', 'missileCommandCrestOrdnanceCrown'],
  },
  fractureCore: {
    buildAccent: [
      'fractureCoreAccentDefault',
      'fractureCoreAccentFractureVein',
      'fractureCoreAccentSingularityVein',
    ],
    buildCrest: ['fractureCoreCrestDefault', 'fractureCoreCrestShatterCrown'],
  },
};

const ARENA_DEFAULT_GLOBAL_COSMETICS: Record<ArenaGlobalCosmeticSlot, ArenaCosmeticId> = {
  banner: 'bannerDefault',
  codexFrame: 'codexFrameDefault',
};

const ARENA_DEFAULT_BUILD_COSMETICS: ArenaBuildValueMap<Record<ArenaBuildCosmeticSlot, ArenaCosmeticId>> = {
  railFocus: {
    buildAccent: 'railFocusAccentDefault',
    buildCrest: 'railFocusCrestDefault',
  },
  novaBloom: {
    buildAccent: 'novaBloomAccentDefault',
    buildCrest: 'novaBloomCrestDefault',
  },
  missileCommand: {
    buildAccent: 'missileCommandAccentDefault',
    buildCrest: 'missileCommandCrestDefault',
  },
  fractureCore: {
    buildAccent: 'fractureCoreAccentDefault',
    buildCrest: 'fractureCoreCrestDefault',
  },
};

const ARENA_UNLOCK_REWARD_COSMETICS: Record<ArenaUnlockId, ArenaCosmeticId> = {
  prismCoreFirstClear: 'bannerPrismShard',
  hiveCarrierFirstClear: 'bannerHiveTrace',
  vectorLoomFirstClear: 'bannerLoomStatic',
  eclipseTalonFirstClear: 'bannerEclipseCut',
  bossTriadComplete: 'codexFrameTriadGrid',
  bossFullRotationComplete: 'codexFrameFullRotation',
  singleRunBossTriadClear: 'bannerTriadBreaker',
  tier24Clear: 'codexFrameEndlessApex',
  tier30Clear: 'codexFrameThreatCartographer',
  tier45Clear: 'bannerDeepCycle',
  tier60Clear: 'codexFrameOuterLimit',
  enemyCodexComplete: 'codexFrameFullSpectrum',
  railFocusMastery4: 'railFocusAccentHalo',
  railFocusMastery8: 'railFocusCrestZenith',
  railFocusMastery10: 'railFocusAccentApexRail',
  novaBloomMastery4: 'novaBloomAccentEcho',
  novaBloomMastery8: 'novaBloomCrestSolarBloom',
  novaBloomMastery10: 'novaBloomAccentSolarCrown',
  missileCommandMastery4: 'missileCommandAccentStrikeMesh',
  missileCommandMastery8: 'missileCommandCrestOrdnanceCrown',
  missileCommandMastery10: 'missileCommandAccentSiegeMesh',
  fractureCoreMastery4: 'fractureCoreAccentFractureVein',
  fractureCoreMastery8: 'fractureCoreCrestShatterCrown',
  fractureCoreMastery10: 'fractureCoreAccentSingularityVein',
};

export function getArenaCosmeticDefinition(cosmeticId: ArenaCosmeticId) {
  return ARENA_COSMETIC_DEFINITIONS[cosmeticId];
}

export function getArenaGlobalCosmeticIds(slot: ArenaGlobalCosmeticSlot) {
  return ARENA_GLOBAL_COSMETIC_ORDER[slot];
}

export function getArenaBuildCosmeticIds(buildId: ArenaBuildId, slot: ArenaBuildCosmeticSlot) {
  return ARENA_BUILD_COSMETIC_ORDER[buildId][slot];
}

export function getArenaDefaultGlobalCosmetic(slot: ArenaGlobalCosmeticSlot) {
  return ARENA_DEFAULT_GLOBAL_COSMETICS[slot];
}

export function getArenaDefaultBuildCosmetic(buildId: ArenaBuildId, slot: ArenaBuildCosmeticSlot) {
  return ARENA_DEFAULT_BUILD_COSMETICS[buildId][slot];
}

export function getArenaUnlockRewardCosmeticId(unlockId: ArenaUnlockId) {
  return ARENA_UNLOCK_REWARD_COSMETICS[unlockId] ?? null;
}

export function createArenaBuildValueMap<T>(factory: (buildId: ArenaBuildId) => T): ArenaBuildValueMap<T> {
  return ARENA_BUILD_ORDER.reduce((accumulator, buildId) => {
    accumulator[buildId] = factory(buildId);
    return accumulator;
  }, {} as ArenaBuildValueMap<T>);
}
